# Generated by Django 5.0.3 on 2024-04-04 06:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='course_name', unique=True)),
                ('course_price', models.CharField(default=None, max_length=10)),
                ('course_offer_price', models.CharField(default=None, max_length=10)),
                ('course_description', models.TextField()),
                ('course_type', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], max_length=10)),
                ('course_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('thumbnail', models.ImageField(blank=True, default='course/default.png', null=True, upload_to='course_thumbnails')),
                ('create_at', models.DateField(auto_now=True, null=True)),
                ('update_at', models.DateField(auto_now=True, null=True)),
                ('delete_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
