# Generated by Django 5.0.3 on 2024-04-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('randomize_questions', models.BooleanField(default=False)),
                ('attempts_allowed', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.course')),
            ],
        ),
    ]
