# Generated by Django 5.0.3 on 2024-04-19 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0005_rename_quizzes_quiz_quizquestion_quizchoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learningapp.quizquestion'),
        ),
    ]
